### ISSUE TITLE
Incorrect README.md

### ISSUE THREAD

**Issue by Sigmanificient** [huntears/amazed#1]
Hi, I was curiously looking through your repositories and found this project.
I wanted to make you aware that the `README.md` seems to be unrelated with the project.

Have a nice day!

**Comment by huntears** [comment]
woops, I still need to do that project x)
Thanks for the heads up :)

**Comment by Sigmanificient** [comment]
![image](https://github.com/huntears/amazed/assets/53050011/7482832b-df63-4971-a13d-2e17245ebb0b)
